## MI ARICHO DE CONFIGURACION BASICA COMO VARIABLES DE ENTORNOS

URL_API_NODE = 'http://localhost:3000/api/v1/loterias'

BOT_NOTIFICACIONES = {
    'TOKEN' : '5482263496:AAHvO_eI-ipwF3n-OLs2wAjNrW3VXwQD-YM'
}

BOT_PREMIAR_MEGALOTTERY = {
    'TOKEN' : '5451666219:AAF3KWQeE1JlC_gK-dYkJpLs_JBFqoa9FGI'
}

#?Configuracion MONGO DB
API_KEY_MONGO_DB = 'raLTadjYvDiA8Yj9GWWAPgJmH3DPFmy2cYLQrntaRoZI9OkyX2Fg3nnDmbkUKdbJ'
