
#! Aqui van el nombre de todas las variables a usar
#?---------------------------
LOTERIA_FLORIDA = 'FLORIDA'
SORTEO_FLORIDA_AM = 'MIDDAY'
SORTEO_FLORIDA_PM = 'EVENING'
#?---------------------------
LOTERIA_NEW_YORK = 'NEW YORK'
SORTEO_NEW_YORK_AM = 'MIDDAY'
SORTEO_NEW_YORK_PM = 'EVENING'

#? ----------------------------------------------------------------------------
LOTERIA_NEW_JERSEY = 'NEW JERSEY'
SORTEO_NEW_JERSEY_AM = 'MIDDAY'
SORTEO_NEW_JERSEY_PM = 'EVENING'
#? ----------------------------------------------------------------------------
LOTERIA_CONNECTICUT = 'CONNECTICUT'
SORTEO_CONNECTICUT_AM = 'MIDDAY'
SORTEO_CONNECTICUT_PM = 'EVENING'
#? ----------------------------------------------------------------------------

LOTERIA_VIRGINIA = 'VIRGINIA'
SORTEO_VIRGINIA_AM = 'MIDDAY'
SORTEO_VIRGINIA_PM = 'EVENING'
#? ----------------------------------------------------------------------------

LOTERIA_WASHINGTON_DC = 'WASHINGTON'
SORTEO_WASHINGTON_DC_AM = 'MIDDAY'
SORTEO_WASHINGTON_DC_PM = 'EVENING'
#? ----------------------------------------------------------------------------
LOTERIA_PENNSYLVANIA = 'PENNSYLVANIA'
SORTEO_PENNSYLVANIA_AM = 'MIDDAY'
SORTEO_PENNSYLVANIA_PM = 'EVENING'
#? ----------------------------------------------------------------------------
LOTERIA_SOUTH_CAROLINA = 'SOUTH CAROLINA'
SORTEO_SOUTH_CAROLINA_AM = 'MIDDAY'
SORTEO_SOUTH_CAROLINA_PM = 'EVENING'
#? ----------------------------------------------------------------------------

OBJ_FL_AM = {
    'LOTERIA': LOTERIA_FLORIDA,
    "SORTEO" : SORTEO_FLORIDA_AM
}

OBJ_FL_PM = {
    'LOTERIA': LOTERIA_FLORIDA,
    "SORTEO" : SORTEO_FLORIDA_PM
}

OBJ_NY_AM = {
    'LOTERIA': LOTERIA_NEW_YORK,
    "SORTEO" : SORTEO_NEW_YORK_AM
}

OBJ_NY_PM = {
    'LOTERIA': LOTERIA_NEW_YORK,
    "SORTEO" : SORTEO_NEW_YORK_PM
}

OBJ_NJ_AM = {
    'LOTERIA': LOTERIA_NEW_JERSEY,
    "SORTEO" : SORTEO_NEW_JERSEY_AM
}

OBJ_NJ_PM = {
    'LOTERIA': LOTERIA_NEW_JERSEY,
    "SORTEO" : SORTEO_NEW_JERSEY_PM
}

OBJ_CT_AM = {
    'LOTERIA': LOTERIA_CONNECTICUT,
    "SORTEO" : SORTEO_CONNECTICUT_AM
}

OBJ_CT_PM = {
    'LOTERIA': LOTERIA_CONNECTICUT,
    "SORTEO" : SORTEO_CONNECTICUT_PM
}

OBJ_VA_AM = {
    'LOTERIA': LOTERIA_VIRGINIA,
    "SORTEO" : SORTEO_VIRGINIA_AM
}

OBJ_VA_PM = {
    'LOTERIA': LOTERIA_VIRGINIA,
    "SORTEO" : SORTEO_VIRGINIA_PM
}

OBJ_DC_AM = {
    'LOTERIA': LOTERIA_WASHINGTON_DC,
    "SORTEO" : SORTEO_WASHINGTON_DC_AM
}

OBJ_DC_PM = {
    'LOTERIA': LOTERIA_WASHINGTON_DC,
    "SORTEO" : SORTEO_WASHINGTON_DC_PM
}

OBJ_PA_AM = {
    'LOTERIA': LOTERIA_PENNSYLVANIA,
    "SORTEO" : SORTEO_PENNSYLVANIA_AM
}

OBJ_PA_PM = {
    'LOTERIA': LOTERIA_PENNSYLVANIA,
    "SORTEO" : SORTEO_PENNSYLVANIA_PM
}

OBJ_SC_AM = {
    'LOTERIA': LOTERIA_SOUTH_CAROLINA,
    "SORTEO" : SORTEO_SOUTH_CAROLINA_AM
}

OBJ_SC_PM = {
    'LOTERIA': LOTERIA_SOUTH_CAROLINA,
    "SORTEO" : SORTEO_SOUTH_CAROLINA_PM
}