PAGES_URL       =   'https://loteriasdominicanas.com/'
FECHA_XPATH     =   '/html/body/div[1]/div[1]/section/div/div[1]/div/div[2]/div/div[1]/div[1]'
NUMERO_1_XPATH  =   '/html/body/div[1]/div[1]/section/div/div[1]/div/div[3]/span[1]'
NUMERO_2_XPATH  =   '/html/body/div[1]/div[1]/section/div/div[1]/div/div[3]/span[2]'
NUMERO_3_XPATH  =   '/html/body/div[1]/div[1]/section/div/div[1]/div/div[3]/span[3]'